apiVersion: v1
kind: Service
metadata:
  name: helloworld-service-nodeport

spec:
  type: NodePort
  ports:
    - port: 5000 
      targetPort: 5000 
      nodePort: 8080 
  selector: 
    app: helloworld
    tier: frontend